backend:
  name: git-gateway
  branch: main

site_url: https://tourmaline-fox-dc1cc1.netlify.app
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ảnh bìa", name: "cover", widget: "image", required: false }
      - label: "Album ảnh"
        name: "gallery"
        widget: "list"
        required: false
        field: { label: "Ảnh", name: "image", widget: "image" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
